{{- if .Values.rbac.enabled }}
{{- $fullName := include "dreamcanvas.fullname" . -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "dreamcanvas.fullname" . }}-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dreamcanvas.labels" . | nindent 4 }}
rules:
  {{- toYaml .Values.rbac.rules | nindent 2 }}
{{- end }}
