{{- if .Values.serviceAccount.create -}}
{{- $fullName := include "dreamcanvas.fullname" . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dreamcanvas.serviceAccountName" . }}
  labels:
    {{- include "dreamcanvas.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
