apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
spec:
  destination:
    namespace: kafka
    server: https://kubernetes.default.svc
  project: kafka
  source:
    chart: kafka
    helm:
      values: |-
        service:
          annotations:
            service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
            service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
            service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "IP"
            external-dns.alpha.kubernetes.io/hostname: "kafka-gameday.brewsentry.com"
            external-dns.alpha.kubernetes.io/ttl: "60"
          type: "LoadBalancer"
        rbac:
          create: true
        externalAccess:
          service:
            type: LoadBalancer
            ports:
              external: 9095
          enabled: true
          autoDiscovery:
            enabled: true
        fullnameOverride: "kafka"
        controller:
          automountServiceAccountToken: true
        listeners:
          client:
            containerPort: 9092
            protocol: PLAINTEXT
            name: CLIENT
            sslClientAuth: ""
          controller:
            name: CONTROLLER
            containerPort: 9093
            protocol: PLAINTEXT
            sslClientAuth: ""
          interbroker:
            containerPort: 9094
            protocol: PLAINTEXT
            name: INTERNAL
            sslClientAuth: ""
          external:
            containerPort: 9095
            protocol: PLAINTEXT
            name: EXTERNAL
            sslClientAuth: ""
        kraft:
          enabled: true
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 30.1.4
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
