apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
spec:
  destination:
    namespace: kafka
    server: https://kubernetes.default.svc
  project: kafka
  source:
    chart: kafka
    helm:
      values: |-
        service:
          annotations:
            service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
            service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
            service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "IP"
            external-dns.alpha.kubernetes.io/hostname: "kafka-gameday.brewsentry.com"
            external-dns.alpha.kubernetes.io/ttl: "60"
          type: "LoadBalancer"
        replicaCount: 3
        zookeeper:
          replicaCount: 3
        listeners:
          external:
            type: loadbalancer
            port: 9092
            authentication:
              type: plaintext
        advertisedListeners:
          external:
            host: kafka-gameday.brewsentry.com
            port: 9092
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 30.1.4
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
