apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
spec:
  destination:
    namespace: kafka
    server: https://kubernetes.default.svc
  project: kafka
  source:
    chart: kafka
    helm:
      parameters:
        - name: replicaCount
          value: '3'
        - name: zookeeper.replicaCount
          value: '3'
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 30.1.4
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
