apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
spec:
  destination:
    namespace: kafka
    server: https://kubernetes.default.svc
  project: kafka
  source:
    chart: kafka
    helm:
      parameters:
        - name: replicaCount
          value: '2'
        - name: zookeeper.replicaCount
          value: '2'
        - name: service.annotations.service\.beta\.kubernetes\.io/aws-load-balancer-type
          value: "nlb"
        - name: service.annotations.service\.beta\.kubernetes\.io/aws-load-balancer-scheme
          value: "internet-facing"
        - name: service.annotations.service\.beta\.kubernetes\.io/aws-load-balancer-nlb-target-type
          value: "IP"
        - name: service.annotations.external-dns\.alpha\.kubernetes\.io/hostname
          value: "kafka-gameday.brewsentry.com"
        - name: service.annotations.external-dns\.alpha\.kubernetes\.io/ttl
          value: "60"
        - name: service.type
          value: "LoadBalancer"
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 30.1.4
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
