{{ range $app, $values := .Values.apps }}
{{- /* guarantees --- is on a newline */ -}}
{{ printf "\n---" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $app }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ $values.namespace }}
    server: https://kubernetes.default.svc
  project: {{ $.Values.project }}
  source:
    path: k8s/charts/dreamcanvas
    repoURL: {{ $.Values.repoUrl }}
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
      {{- with $values.values }}
      values: |- {{ toYaml . | nindent 8 }}
      {{- end }}
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
{{- end }}
